// This file is generated by Slice Machine. Update with care!

import Editorial from './Editorial';
import Product from './Product';

export {
	Editorial,
	Product,
};

export const components = {
	editorial: Editorial,
	product: Product,
};
