import Head from 'next/head'
// import Image from 'next/image'

import View from '../components/View';

export default function Home() {
  return (
    <>
      <Head>
        <title>shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <script async defer src="https://static.cdn.prismic.io/prismic.js?new=true&repo=forcerecs"></script>

    <h5 className="info"><View>acid industrial techno</View></h5>
    </>
  )
}
