import Head from 'next/head'
import Link from 'next/link'
import AudioPlayer from '../components/AudioPlayer';

import Layout from '../components/Layout'
import View from '../components/View';

const music = () => {
  return (
    <>
    <Layout>
      <Head>
        <title>/music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Music</h2>

      <AudioPlayer title="ALONER - sources" url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" />
      <AudioPlayer title="ALONER - else" url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3" />
    </Layout>

    <h5 className="info"><View>Four to the floor</View></h5>
    </>
  )
}

export default music