import Head from 'next/head'
import Link from 'next/link'

import Layout from '../components/Layout'
import View from '../components/View';

const music = () => {
  return (
    <>
    <Layout>
      <Head>
        <title>/music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Music</h2>

      <ul>
        <li>ALONER - sources</li>
      </ul>
    </Layout>

    <h5 className="info"><View>Four to the floor</View></h5>
    </>
  )
}

export default music