import Head from 'next/head'
import Link from 'next/link'

import Layout from '../components/Layout'
import View from '../components/View';

const social = () => {
  return (
    <>
    <Layout>
      <Head>
        <title>/social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Social</h2>

      <ul>
        <li>soundcloud alonermusic</li>
      </ul>

    </Layout>

    <h5 className="info"><View>Offline and online</View></h5>
    </>
  )
}

export default social